addons-gww:
  additionalFlags: ""
  containerTag: rocketpool/graffiti-wall-addon:v1.0.1
  enabled: "false"
  inputUrl: https://cdn-rocketpool.s3.us-west-2.amazonaws.com/graffiti.json
  updateInputTime: "600"
  updatePixelTime: "60"
  updateWallTime: "600"
besu:
  additionalFlags: ""
  containerTag: hyperledger/besu:23.10.0
  jvmHeapSize: "0"
  maxBackLayers: "512"
  maxPeers: "25"
bitflyNodeMetrics:
  bitflyEndpoint: https://beaconcha.in/api/v1/client/metrics
  bitflyMachineName: Smartnode
  bitflySecret: ""
consensusCommon:
  apiPort: "5052"
  checkpointSyncUrl: https://holesky.beaconstate.ethstaker.cc/
  doppelgangerDetection: "true"
  graffiti: Anyting4TheMigas
  openApiPort: closed
  p2pPort: "9001"
executionCommon:
  enginePort: "8551"
  ethstatsLabel: ""
  ethstatsLogin: ""
  httpPort: "8545"
  openRpcPorts: closed
  p2pPort: "30303"
  wsPort: "8546"
exporter:
  additionalFlags: ""
  containerTag: prom/node-exporter:v1.6.1
  enableRootFs: "false"
externalExecution:
  httpUrl: ""
  wsUrl: ""
externalLighthouse:
  additionalVcFlags: ""
  containerTag: rocketpool/lighthouse:b6a78e2-modern
  doppelgangerDetection: "true"
  graffiti: ""
  httpUrl: ""
externalLodestar:
  additionalVcFlags: ""
  containerTag: chainsafe/lodestar:v1.11.3
  doppelgangerDetection: "true"
  graffiti: ""
  httpUrl: ""
externalNimbus:
  additionalVcFlags: ""
  containerTag: statusim/nimbus-validator-client:multiarch-v23.9.1
  doppelgangerDetection: "true"
  graffiti: ""
  httpUrl: ""
externalPrysm:
  additionalVcFlags: ""
  containerTag: rocketpool/prysm:0bd2326
  doppelgangerDetection: "true"
  graffiti: ""
  httpUrl: ""
  jsonRpcUrl: ""
externalTeku:
  additionalVcFlags: ""
  containerTag: consensys/teku:23.10.0
  graffiti: ""
  httpUrl: ""
fallbackNormal:
  ccHttpUrl: ""
  ecHttpUrl: ""
fallbackPrysm:
  ccHttpUrl: ""
  ecHttpUrl: ""
  jsonRpcUrl: ""
geth:
  additionalFlags: ""
  containerTag: ethereum/client-go:v1.13.2
  enablePbss: "false"
  maxPeers: "50"
grafana:
  containerTag: grafana/grafana:9.4.15
  port: "3100"
lighthouse:
  additionalBnFlags: ""
  additionalVcFlags: ""
  containerTag: rocketpool/lighthouse:b6a78e2-modern
  maxPeers: "80"
lodestar:
  additionalBnFlags: ""
  additionalVcFlags: ""
  containerTag: chainsafe/lodestar:v1.11.3
  maxPeers: "50"
mevBoost:
  additionalFlags: ""
  aestusEnabled: "false"
  bloxRouteMaxProfitEnabled: "false"
  bloxRouteRegulatedEnabled: "false"
  containerTag: flashbots/mev-boost:1.6
  edenEnabled: "false"
  enableRegulatedAllMev: "false"
  enableUnregulatedAllMev: "false"
  externalUrl: ""
  flashbotsEnabled: "false"
  mode: local
  openRpcPort: closed
  port: "18550"
  selectionMode: profile
  ultrasoundEnabled: "false"
native:
  ccHttpUrl: ""
  consensusClient: nimbus
  ecHttpUrl: ""
  validatorRestartCommand: ~/.rocketpool/restart-vc.sh
  validatorStopCommand: ~/.rocketpool/stop-validator.sh
nethermind:
  additionalFlags: ""
  additionalModules: ""
  additionalUrls: ""
  cache: "1024"
  containerTag: nethermind/nethermind:1.20.4
  downloadCompleteHistory: "false"
  maxPeers: "50"
  pruneMemSize: "1024"
nimbus:
  additionalBnFlags: ""
  additionalVcFlags: ""
  bnContainerTag: statusim/nimbus-eth2:multiarch-v23.9.1
  containerTag: statusim/nimbus-validator-client:multiarch-v23.9.1
  maxPeers: "160"
  pruningMode: archive
prometheus:
  additionalFlags: ""
  containerTag: prom/prometheus:v2.47.1
  openPort: closed
  port: "9091"
prysm:
  additionalBnFlags: ""
  additionalVcFlags: ""
  bnContainerTag: rocketpool/prysm:0bd2326
  maxPeers: "45"
  openRpcPort: closed
  rpcPort: "5053"
  vcContainerTag: rocketpool/prysm:0bd2326
root:
  bnMetricsPort: "9100"
  consensusClient: lighthouse
  consensusClientMode: local
  ecMetricsPort: "9105"
  enableBitflyNodeMetrics: "false"
  enableMetrics: "true"
  enableMevBoost: "true"
  enableODaoMetrics: "false"
  executionClient: besu
  executionClientMode: local
  exporterMetricsPort: "9103"
  externalConsensusClient: lighthouse
  isNative: "false"
  nodeMetricsPort: "9102"
  reconnectDelay: 60s
  rpDir: ~/.rocketpool
  useFallbackClients: "false"
  vcMetricsPort: "9101"
  version: v1.11.0
  watchtowerMetricsPort: "9104"
smartnode:
  archiveECUrl: ""
  checkpointRetentionLimit: "200"
  dataPath: ~/.rocketpool/data
  distributeThreshold: "1"
  manualMaxFee: "0"
  minipoolStakeGasThreshold: "150"
  network: holesky
  priorityFee: "2"
  projectName: rocketpool
  recordCheckpointInterval: "45"
  recordsPath: ~/.rocketpool/data/records
  rewardsTreeMode: download
  useRollingRecords: "false"
  watchtowerMaxFeeOverride: "200"
  watchtowerPrioFeeOverride: "3"
  web3StorageApiToken: ""
teku:
  additionalBnFlags: ""
  additionalVcFlags: ""
  archiveMode: "false"
  containerTag: consensys/teku:23.10.0
  jvmHeapSize: "0"
  maxPeers: "100"